# Copyright (c) 2016 by CIME Software Ltd.  All rights reserved.

# See: LICENSE.txt for complete licensing information.


version: '2'

networks:
  backend:
    driver: bridge
    
services:
    baikal:
        container_name: calendar
        build: .
        environment:
            CONTAINER_DOMAIN_NAME: "domain.com"
            CONTAINER_HOST_NAME: "calendar"
        ports:
            - "8098:80"
        privileged: true
        volumes:
            - ${PWD}/db:/var/www/calendar_server/Specific/db
        networks:
            - backend
        depends_on:
            - db
    db:
        image: mariadb:5
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;'
        volumes:
          - ./fixtures/database:/docker-entrypoint-initdb.d
        environment:
          MYSQL_ROOT_PASSWORD: baikal
          MYSQL_USER: baikal
          MYSQL_PASSWORD: baikal
          MYSQL_DATABASE: baikal
        networks:
          - backend
     
